services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.6
    restart: unless-stopped
    ports:
      - "${INFLUX_DB_PORT}:${INFLUX_DB_PORT}"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_USER_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_DB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_DB_NAME}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_DB_TOKEN}
    volumes:
      - influxdb:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      influxdb-net:
      grafana-net:

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/log:/var/log/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
    networks:
      grafana-net:

networks:
  influxdb-net:
  grafana-net:

volumes:
  influxdb:
  influxdb-config:
  grafana: