services:
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: iotsensor
      INFLUXDB_ADMIN_ENABLED: true
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-admin}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-helloworldadmin}
      INFLUXDB_USER: ${INFLUXDB_USER:-iotuser}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD:-helloworld}
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-helloworld}
      POSTGRES_DB: ${POSTGRES_DB:-iotdb}
    volumes:
      - ./postgres:/var/lib/postgresql/data