name: Build

on:
  push:
    branches:
    - main
    - develop
    - feat/ci
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    strategy:
      matrix:
        packages: [
          { name: "Emitter", api_name: "emitter" },
          { name: "Receptor", api_name: "receptor" }
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build the ${{ matrix.packages.name }} project
        run: platformio run -e ${{ matrix.packages.api_name }}

      - name: Test the project
        run: platformio check --fail-on-defect high

      - name: Upload the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.packages.name }}-build
          path: .pio/build/${{ matrix.packages.api_name }}