on:
  push:
    branches:
    - main
    - develop
    - feat/ci
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build the receptor project
        run: platformio run -e receptor

      - name: Build the emitter project
        run: platformio run -e emitter

      - name: Test the project
        run: platformio check --fail-on-defect high